### ISSUE TITLE
Update npm module

### ISSUE THREAD

**Issue by Jalepeno112** [wepay/NodeJS-SDK#12]
The version of this SDK on npm is out of date.  It does not reflect the changes made in most recent commit [(e945f250f1d4b416fd5ff0793196f64cbb22c111) ](https://github.com/wepay/NodeJS-SDK/commit/e945f250f1d4b416fd5ff0793196f64cbb22c111).

**Comment by camerona93** [comment]
@Jalepeno112 thanks for pointing this out! Npm now has the [latest version](https://www.npmjs.com/package/wepay) available.

Cheers!
