### ISSUE TITLE
callback argument is a Buffer

### ISSUE THREAD

**Issue by bendavis78** [wepay/NodeJS-SDK#3]
The response should be parsed into object before sending to the callback.

**Comment by wepayer** [comment]
Hi! I'm looking into it.

**Comment by wepayer** [comment]
Hi Ben,

It looks like the fix is easy enough, but we're going to have to make separate release versions since this change would break existing integrations.

I have a pull request opened for this: https://github.com/wepay/NodeJS-SDK/pull/6
