### ISSUE TITLE
/checkout/create response is incomplete

### ISSUE THREAD

**Issue by drsmall** [wepay/NodeJS-SDK#9]
Do to the checkout/call being async
console.log("%s",response) prints:
{"checkout_id":1142912238,"account_id":1484170267,"type":"service","short_description":"Test Checkout","currency":"USD","amount":50,"state":"new","soft_descriptor":"WPY*David Small Stage","auto_capture":true,"create_time":1468179813,"delivery_type":"subscription","gross":0,"reference_id":null,"callback_uri":null,"long_description":null,"fee":{"app_fee":0,"processing_fee":0,"fee_payer":"payer"},"chargeback":{"amount_charged_back":0,"dispute_uri":null},"refund":{"amount_refunded":0,"refund_reason":null},"hosted_checkout":{"checkout_uri":"https:\/\/stage.wepay.com\/api\/checkout\/1142912238\/e5e2b1aa","redirect_uri":null,"shipping_fee":0,"require_shipp

You can see at the end, "require_shipp" is cut off and the rest is missing.

**Comment by y2chaits** [comment]
Fixed in #10
